name: CI

permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches: ['main']
  pull_request:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - run: |
          pnpm gen
          pnpm fmt

          isDiff=$(git --no-pager diff --color --ignore-space-at-eol --ignore-cr-at-eol)

          if [ -n "$isDiff" ]; then
            echo "The following files are not up to date:"
            echo ""
            git diff --name-only | sed 's/^/  - /'
            echo ""
            echo "::error::Generated or formatted files are out of date. Please run 'pnpm gen' and 'pnpm fmt' locally."
            exit 1
          else
            echo "No changes detected. All generated files are up to date."
          fi

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - run: |
          pnpm checks
          pnpm lint
          pnpm fmt:check

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - run: |
          pnpm test

  typedoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - run: pnpm build:docs
