name: CI

permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches: ['main']
  pull_request:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - run: |
          pnpm build
          pnpm gen
          pnpm fmt

          isDiff=$(git --no-pager diff)

          if [ -n "$isDiff" ]; then
            echo "────────────────────────────────────────"
            echo "The following files are not up to date"
            echo "────────────────────────────────────────"
            echo ""
            git diff --name-only \
            | sed 's/^/  - /'
            echo ""
            echo "────────────────────────────────────────"
            echo "Actual diff:"
            echo "────────────────────────────────────────"
            echo ""
            git --no-pager diff
            echo ""
            echo "::error::Generated or formatted files are out of date. Please run 'pnpm gen' and 'pnpm fmt' locally."
            exit 1
          else
            echo "No changes detected. All generated files are up to date."
          fi

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - run: |
          pnpm build
          pnpm checks
          pnpm lint
          pnpm fmt:check

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - run: |
          pnpm build
          pnpm test
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  typedoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - run: |
          pnpm build
          pnpm build:docs
